### ISSUE TITLE
Counts section dont apear with en_US.yml

### ISSUE THREAD

**Issue by MaxRousset** [LuckPerms/locale#2]
The command "lp user info"  don't return the counts section using en_US.yml 

Normal output without lang file :

> 
> [17:11:49 INFO]: [LP] > User Info: kikoo
> [17:11:49 INFO]: [LP] - UUID: bdf58946-0480-37c6-a1a0-89424835f841
> [16:10:53 INFO]: [LP] - Status: Online
> [16:10:53 INFO]: [LP] - Primary Group: villageois
> [16:10:53 INFO]: [LP] - Counts:
> [16:10:53 INFO]: [LP] -    Nodes: 1
> [16:10:53 INFO]: [LP] -    Permissions: 0
> [16:10:53 INFO]: [LP] -    Prefixes: 0
> [16:10:53 INFO]: [LP] -    Suffixes: 0
> [16:10:53 INFO]: [LP] -    Meta: 0
> [16:10:53 INFO]: [LP] - Parent Groups:
> [16:10:53 INFO]: [LP] -    > villageois
> [16:10:53 INFO]: [LP] - Cached Data:
> [16:10:53 INFO]: [LP] -    Has contextual data: true
> [16:10:53 INFO]: [LP] -    Current Contexts: (world=world)
> [16:10:53 INFO]: [LP] -    Current Prefix: ""
> [16:10:53 INFO]: [LP] -    Current Suffix: None

Actual output with en_US.yml :

> 
> [17:11:49 INFO]: [LP] > User Info: kikoo
> [17:11:49 INFO]:  [LP] - UUID: bdf58946-0480-37c6-a1a0-89424835f841
> [17:11:49 INFO]:  [LP] - Status: Offline
> [17:11:49 INFO]:  [LP] - Primary Group: default
> [17:11:49 INFO]: 
> [17:11:49 INFO]: [LP] - Parent Groups:
> [17:11:49 INFO]: [LP] -    > default
> [17:11:49 INFO]: [LP] - Contextual Data:
> [17:11:49 INFO]:  [LP] -    Has contextual data: false
> [17:11:49 INFO]:  [LP] -    Applicable contexts: None
> [17:11:49 INFO]:  [LP] -    Prefix: None
> [17:11:49 INFO]:  [LP] -    Suffix: None
> [17:11:49 INFO]:  [LP] -    Meta: {4}
> [17:11:49 INFO]:

**Comment by lucko** [comment]
The version here is already up-to-date.

You're probably using an outdated version of the plugin.
https://ci.lucko.me/job/LuckPerms/

**Comment by MaxRousset** [comment]
Using the latest version the problem is the same.
I think the problem don't concern directly the plugin but the language file : 

https://github.com/LuckPerms/locale/blob/49dfd485540bca97a0e316fc64c45eca84db5131/en_US.yml

The "counts" section don't appear in the file so it don't appear as output

**Comment by lucko** [comment]
I don't know what you're trying to say.

The counts section was removed in the newer versions of the plugin.

**Comment by MaxRousset** [comment]
> The counts section was removed in the newer versions of the plugin.

Ok so its all good, thanks
