### ISSUE TITLE
lang.yml not working (in some cases)

### ISSUE THREAD

**Issue by beeboy07** [LuckPerms/locale#26]
lang.yml doesn't working in some way, I tried diffrent servers, computers, versions and translations...

Some of values not changing in mine but ex Bermine worked out (even we use same version)

https://discordapp.com/channels/241667244927483904/241667244927483904/754420625279549520
and I also told someone else to try this and he worked out too, he just restarted the server. Last time i tried it on a server and it didn't work, just like my computer

Example, German translation not working too, some of values not changing as same. No error in console and plugin finds lang.yml

**Comment by lucko** [comment]
Hi thanks for reporting this - the locale system in LuckPerms has been recently rewritten. Any issues or bugs with the way the old system worked will no longer apply. :)
