### ISSUE TITLE
Problems with localization

### ISSUE THREAD

**Issue by DarkFort** [LuckPerms/locale#8]
Problems with output to the console of verbose log. Problem occurs when there is a file lang.yml

Should look like:
![image](https://user-images.githubusercontent.com/25278617/43999922-ff6a0ddc-9e1e-11e8-9e27-34a7cb5fe71c.png)

Now:
![image](https://user-images.githubusercontent.com/25278617/44000289-d2b47910-9e25-11e8-88bf-435ab76ae9bf.png)

verbose-log: "&3VB &3&l> {0}"

**Comment by Andre601** [comment]
The only thing I can think of is, that in the localisation-file is a value missing.

What lang-file do you use?

**Comment by DarkFort** [comment]
https://github.com/LuckPerms/locale/blob/master/en_US.yml

**Comment by lucko** [comment]
I've updated en_US
